services:
  mysql_db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_USER:        ${MYSQL_USER}
      MYSQL_PASSWORD:    ${MYSQL_PASSWORD}
      MYSQL_DATABASE:    ${MYSQL_DATABASE}
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u ${MYSQL_USER} -p${MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5

