spring:
  application:
    name: reto
  
  config:
    import: optional:file:.env[.properties]

  r2dbc:
    url: ${DATABASE_URL:r2dbc:mysql://localhost:3306/testdb}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_ROOT_PASSWORD:root}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1