spring:
  application:
    name: webflux-crud
  
  webflux:
    base-path: /api/v1
  
  config:
    import: optional:file:.env[.properties]

  r2dbc:
    url: ${DATABASE_URL:r2dbc:postgresql://localhost:5432/testdb}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1

server:
  port: 8080
  reactive:
    session:
      timeout: 30m
    compression:
      enabled: true
      mime-types: text/html,text/xml,text/plain,application/json

  logging:
    level:
      org.springframework.web: DEBUG
      org.springframework.security: DEBUG
    file:
      name: ${PATH_TEMP:./logs}/app.log
    logback:
      rollingpolicy:
        max-file-size: 10MB
        max-history: 30
